geo-builder:
  build: .
  environment:
    PROJ_VERSION: "4.8.0"
    GDAL_VERSION: "1.11.1"
    GEOS_VERSION: "3.4.2"
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    STACK: "cedar-14"
    S3_BUCKET: "lomotif-heroku"
  command: bash -c './geo-build'
  volumes:
    - ./build:/tmp